# Generated by Django 4.2.11 on 2026-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_path', models.CharField(max_length=1024)),
                ('top_result_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('top_similarity', models.FloatField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
            ],
        ),
    ]
