# Generated by Django 4.2.11 on 2026-01-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0002_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1024)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
