# Generated by Django 4.2.11 on 2026-01-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='SearchHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('score', models.FloatField()),
                ('rank', models.IntegerField(default=0)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='image_search.searchhistory')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
