# Generated by Django 4.2.11 on 2026-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0004_favorite_tags_searchhistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='query_web_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
