# Generated by Django 4.2.11 on 2026-01-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0005_searchhistory_query_web_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('url', models.TextField()),
                ('score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_image', models.ImageField(blank=True, null=True, upload_to='queries/')),
                ('query_feat', models.BinaryField(blank=True, null=True)),
                ('feat_dim', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='history',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='similarity',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='tags',
        ),
        migrations.AddField(
            model_name='favorite',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='SearchHistoryItem',
        ),
        migrations.AddField(
            model_name='historyitem',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='image_search.historyrecord'),
        ),
    ]
