# Generated by Django 6.0 on 2026-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0006_historyitem_historyrecord_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyrecord',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='historyitem',
            name='quality',
            field=models.CharField(default='Poor', max_length=10),
        ),
    ]
