# Generated by Django 4.2.11 on 2026-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0007_alter_historyrecord_options_historyitem_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
